export const sidebarItems = [
    { id: "pengenalanPython", label: "Pengenalan Python", path: "/pengenalanPython" },
    { id: "VariabelTipeData", label: "Variabel & Tipe Data", path: "/VariabelTipeData" },
    { id: "Operator", label: "Operator", path: "/Operator" },
    { id: "Kondisi", label: "Kondisi", path: "/Kondisi" },
    { id: "Perulangan", label: "Perulangan", path: "/Perulangan" },
    { id: "Fungsi", label: "Fungsi", path: "/Fungsi" },
    { id: "strukturData", label: "Struktur Data", path: "/strukturData" },
    { id: "Comprehension", label: "Comprehension", path: "/Comprehension" },
    { id: "String", label: "String", path: "/String" },
    { id: "file_io", label: "File I/O", path: "/file_io" },
    { id: "modulePackage", label: "Module & Package", path: "/modulePackage" },
    { id: "OOP", label: "OOP", path: "/OOP" },
    { id: "errorHandeling", label: "Error Handling", path: "/errorHandeling" },
    { id: "Decorator", label: "Decorator", path: "/Decorator" },
    { id: "virtualEnvPip", label: "Virtualenv & Pip", path: "/virtualEnvPip" },
    { id: "Testing", label: "Testing", path: "/Testing" },
    { id: "Debugging", label: "Debugging", path: "/Debugging" },
    { id: "typeHints", label: "Type Hints", path: "/typeHints" },
    { id: "StandardLibary", label: "Standard Library", path: "/StandardLibary" },
  ];